name: Cypress Tests

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Spotify
    steps:
      
    - name: Checkout code
      uses: actions/checkout@v2
      

    - name: Install Dependencies
      run: npm install
      
    
    - name: Run Smoke Tests
      env:
          CYPRESS_browser: "chrome"
      run: npx cypress run 
